# Generated by Django 4.0.1 on 2022-01-19 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.cabinet')),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.office'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateTimeField(verbose_name='Start of booking')),
                ('datetime_to', models.DateTimeField(verbose_name='End of booking')),
                ('comment', models.CharField(max_length=10000, verbose_name='Booker comment')),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookers', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='book_app.office', verbose_name='Office')),
            ],
        ),
    ]
