# Generated by Django 4.0.1 on 2022-01-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_remove_booking_office_booking_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Booker comment'),
        ),
    ]
